sudo: required
language: ruby
services:
  - docker
branches:
    only:
        - master
install:
  - apt-get install python-pip python-dev
  - pip install -U docker-compose
notifications:
    recipients:
        - lunnlew@gmail.com
    email:
        on_success: change
        on_failure: always
