before_install:
  - curl -sSL https://get.docker.com/ | sh
branches:
    only:
        - master
before_script:
 - chmod +x scripts/build-latest.sh
 - chmod +x scripts/deploy-latest.sh
script:
  - scripts/build-latest.sh
  - scripts/deploy-latest.sh
notifications:
    recipients:
        - lunnlew@gmail.com
    email:
        on_success: change
        on_failure: always
