sudo: required
language:
  - ruby
  - python
services:
  - docker
branches:
    only:
        - master
#install:
#  - sudo apt-get install python-pip python-dev -y
#  - sudo pip install -U -I docker-compose==1.6.2
before_script:
  - curl -L https://github.com/docker/compose/releases/download/1.5.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - chmod +x scripts/build-latest.sh
  - chmod +x scripts/deploy-latest.sh
script:
  - scripts/build-latest.sh
  - docker run --name shadowsocks-server -d -p 8388:8388/tcp -p 8388:8388/udp -e PASSWORD=5ouMnqPyzseL -e METHOD=aes-256-cfb --restart always lunnlew/shadowsocks-server
  - docker ps | grep -q shadowsocks-server
notifications:
    recipients:
        - lunnlew@gmail.com
    email:
        on_success: change
        on_failure: always
